//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWind.Sales.Backend.UseCases.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreateOrderMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateOrderMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NorthWind.Sales.Backend.UseCases.Resources.CreateOrderMessages", typeof(CreateOrderMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El identificador de cliente proporcionado no existe..
        /// </summary>
        internal static string CustomerIdNotFoundError {
            get {
                return ResourceManager.GetString("CustomerIdNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cliente {0} tiene un adeudo pendiente de {1}..
        /// </summary>
        internal static string CustomerWithBalanceErrorTemplate {
            get {
                return ResourceManager.GetString("CustomerWithBalanceErrorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creación de orden {0} cancelada..
        /// </summary>
        internal static string OrderCreationCancelledTemplate {
            get {
                return ResourceManager.GetString("OrderCreationCancelledTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El producto {0} no existe..
        /// </summary>
        internal static string ProductIdNotFoundErrorTemplate {
            get {
                return ResourceManager.GetString("ProductIdNotFoundErrorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orden de compra {0} creada..
        /// </summary>
        internal static string PurchaseOrderCreatedTemplate {
            get {
                return ResourceManager.GetString("PurchaseOrderCreatedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha creado la orden {0} con {1} productos..
        /// </summary>
        internal static string SendEmailBodyTemplate {
            get {
                return ResourceManager.GetString("SendEmailBodyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orden especial creada.
        /// </summary>
        internal static string SendEmailSubject {
            get {
                return ResourceManager.GetString("SendEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de creación de orden de compra.
        /// </summary>
        internal static string StartingPurchaseOrderCreation {
            get {
                return ResourceManager.GetString("StartingPurchaseOrderCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad {0} de {1} no suficiente para producto {2}..
        /// </summary>
        internal static string UnitsInStockLessThanQuantityErrorTemplate {
            get {
                return ResourceManager.GetString("UnitsInStockLessThanQuantityErrorTemplate", resourceCulture);
            }
        }
    }
}
