//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWind.Membership.Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserRegistrationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserRegistrationMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NorthWind.Membership.Entities.Resources.UserRegistrationMessages", typeof(UserRegistrationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato de correo no es válido..
        /// </summary>
        internal static string InvalidEmailErrorMessage {
            get {
                return ResourceManager.GetString("InvalidEmailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se requiere al menos un dígito en la contraseña.
        /// </summary>
        internal static string PasswordRequiresDigitErrorMessage {
            get {
                return ResourceManager.GetString("PasswordRequiresDigitErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se requiere al menos un caracter minuscula en la contraseña.
        /// </summary>
        internal static string PasswordRequiresLowerErrorMessage {
            get {
                return ResourceManager.GetString("PasswordRequiresLowerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se requiere al menos un caracter no alfanumérico en la contraseña.
        /// </summary>
        internal static string PasswordRequiresNonAlphanumericErrorMessage {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se requiere al menos un caracter mayúscula en la contraseña.
        /// </summary>
        internal static string PasswordRequiresUpperErrorMessage {
            get {
                return ResourceManager.GetString("PasswordRequiresUpperErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se requiere al menos 6 caracteres en la contraseña.
        /// </summary>
        internal static string PasswordTooShortErrorMessage {
            get {
                return ResourceManager.GetString("PasswordTooShortErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo es requerido..
        /// </summary>
        internal static string RequiredEmailErrorMessage {
            get {
                return ResourceManager.GetString("RequiredEmailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre es requerido..
        /// </summary>
        internal static string RequiredFirstNameErrorMessage {
            get {
                return ResourceManager.GetString("RequiredFirstNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido es requerido..
        /// </summary>
        internal static string RequiredLastNameErrorMessage {
            get {
                return ResourceManager.GetString("RequiredLastNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña es requerida..
        /// </summary>
        internal static string RequiredPasswordErrorMessage {
            get {
                return ResourceManager.GetString("RequiredPasswordErrorMessage", resourceCulture);
            }
        }
    }
}
